minimum_pre_commit_version: "4.3.0"

default_language_version:
  python: python3

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: local
    hooks:
      - id: docker-compose-linter
        name: docker-compose-linter
        entry: dclint
        language: node
        additional_dependencies: [ dclint@3.1.0 ]
        files: (docker-)?compose.*\.ya?ml$
        args: [ "--fix", "--recursive" ]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        exclude: .envrc

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: [ -i, "2", -ci ]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        exclude: "(docker-)?compose.*\\.ya?ml$"

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-fix
        args: [ --fix ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-added-large-files
        args: [ --maxkb, "1000" ]

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args: [ --update-only ]
